export const SliderDatBgd = [
    {
      src:
      "../src/assets/bg/bgd2.jpg"
    },
    {
      src:
      "../src/assets/bg/bgd2.jpg"
    },
    {
      src:
      "../src/assets/bg/bgd2.jpg"
    },
    {
      src:
      "../src/assets/bg/bgd2.jpg"
    },
    {
      src:
      "../src/assets/bg/bgd2.jpg"
    }
  ];